"""empty message

Revision ID: 31473a72df2a
Revises: 45913faf6e59
Create Date: 2020-03-17 01:06:43.639549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31473a72df2a'
down_revision = '45913faf6e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('surname', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('passwordHash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=True)
    op.create_index(op.f('ix_employee_name'), 'employee', ['name'], unique=False)
    op.create_index(op.f('ix_employee_surname'), 'employee', ['surname'], unique=False)
    op.create_table('facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facilityName', sa.String(length=30), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facilityName')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activityType', sa.String(length=20), nullable=True),
    sa.Column('facilityId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facilityId'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookingDate', sa.DateTime(), nullable=True),
    sa.Column('bookingTime', sa.Integer(), nullable=True),
    sa.Column('facilityId', sa.Integer(), nullable=True),
    sa.Column('customerId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customerId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['facilityId'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookingId', sa.Integer(), nullable=True),
    sa.Column('currentCapacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bookingId'], ['booking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('dateOfPurchase', sa.DateTime(), nullable=True),
    sa.Column('customerId', sa.Integer(), nullable=True),
    sa.Column('bookingId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bookingId'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['customerId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_dateOfPurchase'), 'receipt', ['dateOfPurchase'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_dateOfPurchase'), table_name='receipt')
    op.drop_table('receipt')
    op.drop_table('counter')
    op.drop_table('booking')
    op.drop_table('activity')
    op.drop_table('facility')
    op.drop_index(op.f('ix_employee_surname'), table_name='employee')
    op.drop_index(op.f('ix_employee_name'), table_name='employee')
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
