"""empty message

Revision ID: 45913faf6e59
Revises: 00325de0b951
Create Date: 2020-03-16 20:20:11.207407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45913faf6e59'
down_revision = '00325de0b951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    # ### end Alembic commands ###
