"""empty message

Revision ID: 3a68082c83cb
Revises: 
Create Date: 2020-04-21 18:04:09.128778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a68082c83cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('surname', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('passwordHash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=True)
    op.create_index(op.f('ix_employee_name'), 'employee', ['name'], unique=False)
    op.create_index(op.f('ix_employee_surname'), 'employee', ['surname'], unique=False)
    op.create_table('facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facilityName', sa.String(length=30), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facilityName')
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('day', sa.String(length=25), nullable=True),
    sa.Column('startTime', sa.String(length=25), nullable=True),
    sa.Column('endTime', sa.String(length=25), nullable=True),
    sa.Column('facility', sa.String(length=25), nullable=True),
    sa.Column('activity', sa.String(length=25), nullable=True),
    sa.Column('availability', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('surname', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('DateOfBirth', sa.Date(), nullable=True),
    sa.Column('CCD', sa.String(length=40), nullable=True),
    sa.Column('CVV', sa.String(length=40), nullable=True),
    sa.Column('DateOfExpire', sa.DateTime(), nullable=True),
    sa.Column('paymentIntervals', sa.String(length=20), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=15), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activityType', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('facilityId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facilityId'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookingDate', sa.DateTime(), nullable=True),
    sa.Column('sessionId', sa.Integer(), nullable=True),
    sa.Column('customerId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customerId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sessionId'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookingDate', sa.DateTime(), nullable=True),
    sa.Column('bookingTime', sa.Integer(), nullable=True),
    sa.Column('facilityId', sa.Integer(), nullable=True),
    sa.Column('bookingId', sa.Integer(), nullable=True),
    sa.Column('currentCapacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bookingId'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['facilityId'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=25), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('dateOfPurchase', sa.DateTime(), nullable=True),
    sa.Column('customerId', sa.Integer(), nullable=True),
    sa.Column('bookingId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bookingId'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['customerId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_dateOfPurchase'), 'receipt', ['dateOfPurchase'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_dateOfPurchase'), table_name='receipt')
    op.drop_table('receipt')
    op.drop_table('counter')
    op.drop_table('booking')
    op.drop_table('activity')
    op.drop_table('user')
    op.drop_table('session')
    op.drop_table('facility')
    op.drop_index(op.f('ix_employee_surname'), table_name='employee')
    op.drop_index(op.f('ix_employee_name'), table_name='employee')
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
